//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAGestaoCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNOS
    {
        public string CPF_ALUNO { get; set; }
        public string NOME_ALUNO { get; set; }
        public string END_ALUNO { get; set; }
        public string ESTADO_ALUNO { get; set; }
        public string MUNICIPIO_ALUNO { get; set; }
        public string TEL_ALUNO { get; set; }
        public string EMAIL_ALUNO { get; set; }
        public string SENHA_ALUNO { get; set; }
    }
}
